"""baseline pre-PR8 (esquema ff0825b)

Revision ID: 0001
Revises: 
Create Date: 2026-05-16 21:24:37.579251
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administradores',
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contrasena', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_admin')
    )
    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_administradores_correo'), ['correo'], unique=True)

    op.create_table('clinicas',
    sa.Column('id_clinica', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clues', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('colonia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('municipio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_clinica'),
    sa.UniqueConstraint('clues')
    )
    with op.batch_alter_table('clinicas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinicas_colonia'), ['colonia'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinicas_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinicas_municipio'), ['municipio'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinicas_nombre'), ['nombre'], unique=False)

    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_rol')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_nombre'), ['nombre'], unique=True)

    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_clinica', sa.Integer(), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paterno', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('materno', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('correo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contrasena', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_clinica'], ['clinicas.id_clinica'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_correo'), ['correo'], unique=True)

    op.create_table('farmaceuticos',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('licencia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('turno', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('licencia')
    )
    op.create_table('llaves',
    sa.Column('id_llave', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('llave_publica', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_llave')
    )
    op.create_table('medicos',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('cedula', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('especialidad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('universidad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    with op.batch_alter_table('medicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicos_cedula'), ['cedula'], unique=True)

    op.create_table('pacientes',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('curp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nacimiento', sa.Date(), nullable=False),
    sa.Column('sexo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tel_emergencia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pacientes_curp'), ['curp'], unique=True)

    op.create_table('recetas',
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_farmaceutico', sa.Integer(), nullable=True),
    sa.Column('capsula_cifrada', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('iv_aes_gcm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accesos', sa.JSON(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_farmaceutico'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_medico'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_receta')
    )
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recetas_id_farmaceutico'), ['id_farmaceutico'], unique=False)
        batch_op.create_index(batch_op.f('ix_recetas_id_medico'), ['id_medico'], unique=False)
        batch_op.create_index(batch_op.f('ix_recetas_id_paciente'), ['id_paciente'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recetas_id_paciente'))
        batch_op.drop_index(batch_op.f('ix_recetas_id_medico'))
        batch_op.drop_index(batch_op.f('ix_recetas_id_farmaceutico'))

    op.drop_table('recetas')
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pacientes_curp'))

    op.drop_table('pacientes')
    with op.batch_alter_table('medicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicos_cedula'))

    op.drop_table('medicos')
    op.drop_table('llaves')
    op.drop_table('farmaceuticos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_correo'))

    op.drop_table('usuarios')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_nombre'))

    op.drop_table('roles')
    with op.batch_alter_table('clinicas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinicas_nombre'))
        batch_op.drop_index(batch_op.f('ix_clinicas_municipio'))
        batch_op.drop_index(batch_op.f('ix_clinicas_estado'))
        batch_op.drop_index(batch_op.f('ix_clinicas_colonia'))

    op.drop_table('clinicas')
    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_administradores_correo'))

    op.drop_table('administradores')
    # ### end Alembic commands ###
